apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.service }}
  labels:
    app: {{ .Values.api.label }}
spec:
  type: {{ .Values.api.serviceType }}
  selector:
    app: {{ .Values.api.label }}
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.label }}
      protocol: TCP
