apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ui.service }}
  labels:
    app: {{ .Values.ui.label }}
spec:
  type: {{ .Values.ui.serviceType }}
  selector:
    app: {{ .Values.ui.label }}
  ports:
    - port: {{ .Values.ui.port }}
      targetPort: {{ .Values.ui.port }}
      protocol: TCP
